management:
  endpoints:
    web:
      exposure:
        include: "*"
 
spring: 
  profiles:
    active: dev
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
 
greetingLanguage: English

---
spring: 
  profiles: dev
greetingLanguage: French
---
spring: 
  profiles: prod
greetingLanguage: Spanish
